not ready
TZagoruikoe/tspp_homework pull request #7
Opened 2024-11-11 22:11 UTC by TZagoruikoe

Добрый вечер.

Вы не могли бы, пожалуйста, посмотреть код? Не понимаю, в каком месте делаю что-то не так, но мне не нравится, как прыгает норма при запуске: на 1 процессе - 0,514255, но при этом на 8 - 0,000038.
У меня косяк с логикой вычислений или я что-то не так при обмене сообщениями делаю?

2024-11-11 22:50 UTC, dimlichmanov requested changes
Я гляну завтра, подскажите, у вас из total_rows строк верхняя выделяется на приём сообщения сверху, а нижняя - на приём снизу?

2024-11-12 06:49 UTC, TZagoruikoe commented
Да, все верно.

2024-11-12 14:22 UTC, dimlichmanov requested changes
Вроде вот так, но мог ещё упустить. Обмены вроде верные.

2024-11-12 14:22 UTC, dimlichmanov commented on sem07/task.c
> +    initialize_grid(grid, rows_per_process, N);
initialize_grid(grid, total_rows , N);

2024-11-12 14:22 UTC, dimlichmanov commented on sem07/task.c
> +        for (int i = 1; i < rows_per_process - 1; i++) {
i < total_rows

2024-11-12 14:23 UTC, dimlichmanov commented on sem07/task.c
> +        for (int i = 1; i < rows_per_process - 1; i++) {
i < total_rows - 1

2024-11-16 20:18 UTC, TZagoruikoe commented
Добрый вечер.

Проверьте, пожалуйста, задание.

И еще сразу хотела уточнить по поводу следующей задачи: если ее нужно будет сдавать на паре, программу нужно будет запускать? Или можно будет в github по коду пройтись? (у меня виртуалка на ноутбуке, он тяжелый, так что в университет я планшет ношу. И мне нужно понимать, понадобится ли мне другая машина для сдачи)

2024-11-16 21:07 UTC, dimlichmanov commented
Здравствуйте! Я могу посмотреть и запустить со своей машины, приносить свою не имеет необходимости.
Главное - снабдить решение своими устными комментариями при сдаче.

2024-11-16 21:25 UTC, dimlichmanov approved these changes

2024-11-16 21:26 UTC, closed without merging